# name: Install awscli and awsebcli on Mac

on: 
  push

jobs:
  test1:
     name: Install ta-lib
     runs-on: macos-latest
     steps:
       - uses: actions/checkout@master
       - name: Install ta-lib
         run: |
           brew install ta-lib
           /Library/Frameworks/Python.framework/Versions/3.11/bin/python -m pip install --upgrade pip
           pip3 install ta-lib 
           

       - name: Check ta-lib install
         run: |
          python3 -c "import talib as ta; print(dir(ta))"
