# name: Install awscli and awsebcli on Mac

on: 
  push

jobs:
  test1:
     name: Install Brew && ta-lib
     runs-on: macos-latest
     steps:
       - uses: actions/checkout@master
       - name: Install ta-lib
         run: |
           brew update
           brew upgrade
           brew install ta-lib 

       - name: Check ta-lib install
         run: |
          python -c "import ta-lib as ta; print(dir(ta))"
