# name: Install awscli and awsebcli on Mac

on: 
  push

jobs:
  test1:
     name: Install Brew
     runs-on: macos-latest
     steps:
       - uses: actions/checkout@master

       - name: Install numpy
         run: |
           brew update
           brew upgrade
           brew install numpy

       - name: Check Brew install
         run: |
          brew update
          brew upgrade
          brew cleanup
          python -c "import numpy as np; print(np.version.git_revision)"
