# name: Install awscli and awsebcli on Mac

on: 
  push

jobs:
  test1:
     name: Install Brew && ta-lib
     runs-on: macos-latest
     steps:
       - uses: actions/checkout@master
       - name: Install ta-lib
         run: |
           brew install ta-lib
           brew link --overwrite go
           pip install talib 
           

       - name: Check ta-lib install
         run: |
          python -c "import talib as ta; print(dir(ta))"
